# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            This Little World
tagline:          ~ a Shakesperean page
url:              http://thislittleworld.github.io
paginate:         3
paginate_path:    "/blog/page:num/"
baseurl:          /
author:
  name:           Aviva Flyax
  url:            https://github.com/avivatf
  email:          avivatf@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thislittleworld/

# This is the list of pages to include in the header of the website.
pages_list:       
  Plays:  '/plays/'
  Biography:  '/biography/'
  Critics:  '/critics/'
  World:  '/world/'
  Blog: '/blog/'
  About: '/about/'
  Archive: '/archive/'
  # Feed: '/atom.xml'

# # Allow URL Redirects: 
# #  * https://help.github.com/articles/redirects-on-github-pages
# gems:
#   - jekyll-redirect-from
