# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            This Little World
tagline:          ~ a Shakesperean page
url:              http://thislittleworld.github.io
paginate:         5
paginate_path:    "/blog/page:num/"
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thislittleworld/
