# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            This Little World
tagline:          "Inside Shakespeare's world"
description:      ''
url:              http://thislittleworld.github.io

author:
  name:           'Aviva Flyax'
  url:            http://thislittleworld.github.io

paginate:         5

# Custom vars
github:
  repo:           https://github.com/avivatf
